apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "$APP-$GITHUB_REF:11-deployment"
  namespace: "default"
  labels:
    app: "treetracker-web-map-api"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "treetracker-web-map-api"
  template:
    metadata:
      labels:
        app: "treetracker-web-map-api"
    spec:
      containers:
      - name: "treetracker-web-map-api"
        image: "ximena9210/treetracker-web-map-api:test-release"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: treetracker-web-map-api
  name: treetracker-web-map-api-test-release-deployment-service
  namespace: default
spec:
  ports:
  - name: treetracker-web-map-api
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: treetracker-web-map-api
  type: NodePort
