apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: treetracker-webmap-api-test-release-ingress
  namespace: default
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: treetracker-webmap-api-test-release-service
          servicePort: 80
