name: Build treetracker-web-map.

on:
  release:
    types: [published]

  push:
    branches:
    - test-release

  pull_request:
    branches:
    - test-release

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v1
      - name: "Login to DockerHub Registry"
        run: "echo  ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin"
      - name: "Get the version"
        id: vars
        run: "echo ::set-output name=tag::$(echo ${GITHUB_REF:11})"
      - name: "Build the tagged Docker Nginx"
        run: "docker build . -f ./Dockerfile.Nginx -t treetracker-webmap-nginx:latest"
      - name: "Build the tagged Docker image API"
        run: "docker build . -f ./Dockerfile -t treetracker-webmap-api"
      - name: "Tag docker-image API"  
        run: "docker build . -f ./Dockerfile  -t ximena9210/treetracker-webmap-api:${{steps.vars.outputs.tag}}"
      - name: "Push the tagged Docker image API"
        run: "docker push ximena9210/treetracker-webmap-api:${{steps.vars.outputs.tag}}"
      - name: Install doctl for kubernetes
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}
      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save treetracker-experimental-cluster
      - name: Creating service and deployment in k8
        run: kubectl apply -f ./deploy/k8/deployment.yml
      - name: Creating ingress in k8
        run: kubectl apply -f ./deploy/k8/ingress.yml
